name: Checks
on:
  push:
    branches:
      - master
      - next
  pull_request:
    branches:
      - master
      - next

env:
  # reduces noise from npm post-install scripts
  DISABLE_OPENCOLLECTIVE: true
  OPEN_SOURCE_CONTRIBUTOR: true

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Commit Linter
        uses: wagoid/commitlint-github-action@v1.3.1
        with:
          configFile: './package.json'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-node:
    name:
      # prettier-ignore
      Test on Node.js v${{ matrix.node-version }} and eslint v${{matrix.eslint-version }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [8.x, 10.x, 12.x, 13.x, 14.x]
        eslint-version: [6, 7]
        exclude:
          # eslint@7 doesn't support node@8
          - node-version: 8.x
            eslint-version: 7
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install with eslint v${{matrix.eslint-version }}
        run: |
          npm ci
          npm install -D eslint@${{matrix.eslint-version }}
      - name: prettier
        run: npm run prettier:check
      - name: typecheck
        run: npm run typecheck
      - name: test
        run: npm run test --coverage
        env:
          CI: true

  test-os:
    name: Test on ${{ matrix.os }} using Node.js LTS
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: install
        run: npm ci
      - name: prettier
        run: npm run prettier:check
      - name: typecheck
        run: npm run typecheck
      - name: test
        run: npm run test --coverage
        env:
          CI: true
