name: Release
on:
  push:
    branches:
      - master

env:
  # reduces noise from npm post-install scripts
  DISABLE_OPENCOLLECTIVE: true
  OPEN_SOURCE_CONTRIBUTOR: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          cache: npm

      - name: install
        run: npm ci
      - name: prettier
        run: npm run prettier:check
      - name: typecheck
        run: npm run typecheck
      - name: test
        run: npm run test --coverage
        env:
          CI: true

      - name: release
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
